function T = Inverse_Leg_Dynamics(target_q_state)
q = target_q_state(1:3,1)
qd = target_q_state(4:6,1)
qdd = target_q_state(7:9,1)
ardent_leg = Leg_Info()
T = ardent_leg.rne([q(1) q(2) q(3)], [qd(1) qd(2) qd(3)], [qdd(1) qdd(2) qdd(3)])
